import Head from "next/head";
import Navbar from "@/components/navbar/Navbar";
import Script from "next/script";

const Home = () => {
  return (
    <>
      <Head>
        <title>Aamir Khan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script
        src="https://unpkg.com/ionicons@4.5.10-0/dist/ionicons/ionicons.esm.js"
        type="module"
      />
      <Script
        src="https://unpkg.com/ionicons@4.5.10-0/dist/ionicons/ionicons.js"
        nomodule=""
        defer
      />
      <Navbar />
    </>
  );
};

export default Home;
